### ISSUE TITLE
Morning Sessions

### ISSUE THREAD

**Issue by jaflih** [matovu-farid/My-Portfolio#6]
Morning Sessions 
2 December 2021

**Comment by jaflih** [comment]
> Morning Sessions 2 December 2021

Please compare your design and the template design and try to have a background to match the template

Your :

<img width="440" alt="Capture d’écran 2021-12-02 à 08 25 45" src="https://user-images.githubusercontent.com/7243132/144376035-609e4479-fcdc-43cb-8c5e-01820186cc83.png">

Figma template : 


<img width="407" alt="Capture d’écran 2021-12-02 à 08 25 24" src="https://user-images.githubusercontent.com/7243132/144376068-eaa346a6-a77e-44c0-a5fc-02277a0e2788.png">

**Comment by VSeray** [comment]
Great job 🎉 but I do recommend you follow the design on Figma more thoroughly, since I think this is a great technique for enhancing User Experience on a web page.

**Comment by jaflih** [comment]
Please compare your design and the template design and try to have a background to match the template.

Your
<img width="1067" alt="Capture d’écran 2021-12-02 à 08 44 45" src="https://user-images.githubusercontent.com/7243132/144378792-e150d095-28ba-456d-be60-c75ea8d4f2d9.png">

Figma : 

<img width="723" alt="Capture d’écran 2021-12-02 à 08 45 21" src="https://user-images.githubusercontent.com/7243132/144378830-160fbfd3-7e08-4b52-8426-aed48075797a.png">

The problem can be fixed with using 1 `ul` ( flexbox => flex-wrap and align-item ) 

<img width="374" alt="Capture d’écran 2021-12-02 à 08 47 06" src="https://user-images.githubusercontent.com/7243132/144378948-dc4fbb90-cff1-4ac2-ae71-afb62b2ea748.png">

**Comment by HAMMAS-SALEEM** [comment]
You should use headings in you each component
